# Generated by Django 3.1.2 on 2021-04-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
