# Generated by Django 3.1.2 on 2021-04-05 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0002_section_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
        migrations.AddField(
            model_name='blog',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
