# Generated by Django 3.1.2 on 2021-04-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0003_auto_20210405_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posted',
        ),
    ]
