# Generated by Django 3.1.2 on 2021-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0004_remove_blog_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='myBlog', max_length=64),
            preserve_default=False,
        ),
    ]
