# Generated by Django 3.1.2 on 2021-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0005_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-04-09'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
