# Generated by Django 3.1.2 on 2021-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0006_auto_20210409_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='heading',
            field=models.CharField(default='sex', max_length=64),
            preserve_default=False,
        ),
    ]
