# Generated by Django 3.1.2 on 2021-04-13 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0007_blog_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='blogs_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
