# Generated by Django 3.1.2 on 2021-04-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0008_auto_20210414_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_count',
        ),
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
