# Generated by Django 3.1.2 on 2021-04-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0010_auto_20210414_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='paragraph',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
